[workspace]
members = [
    "glace",
    "glace-grr",
    "glace-grr/shader",
    "glace-vk",
    "glace-vk/shader",
]

[profile.dev]
opt-level = 1

[profile.dev.build-override]
opt-level = 3

[profile.release.build-override]
opt-level = 3
