[workspace]
members = [
    "glace",
    "glace-grr",
    "glace-grr/shader",
    "glace-vk",
    "glace-vk/shader",
]

[profile.release]
incremental = true
codegen-units = 256

[profile.dev.build-override]
opt-level = 3

[profile.release.build-override]
opt-level = 3
incremental = true
codegen-units = 256
